#ifndef STRINGS_HPP
#define STRINGS_HPP

#define ERR_ORDER_ALREADY_EXISTS "ERR 01 <ORDER_ID_ALREADY_EXISTS>"
#define ERR_ORDER_DOES_NOT_EXIST "ERR 02 <ORDER_DOES_NOT_EXIST>"
#define ERR_INVALID_DATA "ERR 03 <ERR_INVALID_DATA>"

#define MESSAGE_ACCEPTED "ACCEPTED"
#define MESSAGE_REJECTED "REJECTED"

#define SUCC_NEW_ORDER_CREATED "SUCC 01 <NEW_ORDER_CREATED>"
#define SUCC_ORDER_DELETED "SUCC 02 <ORDER_DELETED>"
#define SUCC_ORDER_QUANTITY_MODIFIED "SUCC 03 <ORDER_QUANTITY_MODIFIED>"
#define SUCC_TRADE_EXECUTED "SUCC 04 <TRADE_EXECUTED>"

#define WARN_NEW_ORDER_REJECTED "WARN 01 <NEW_ORDER_REJECTED>"
#define WARN_MODIFY_ORDER_REJECTED "WARN 02 <WARN_MODIFY_ORDER_REJECTED>"

#endif